### PR TITLE
Maintenance

### PR DESCRIPTION
**Pull request by Avaq**
- Merge Fluture template
- Update dependency range of Fluture

### CODE REVIEW

**Comment by Avaq** [comment]
I'd like to merge https://github.com/fluture-js/fluture-template/pull/7 before moving forward with this one.

**Comment by Avaq** [comment]
A funny example of the disconnect between the decentralised git model vs the centralised git model is that the merge commit messages generated in the fluture-template repo now don't carry over the issue number references correctly to the fluture-node repository. I guess Github assumed that its own context was the only context where this commit would appear when it generated that message.

**Comment by dicearr** [comment]
> A funny example of the disconnect between the decentralised git model vs the centralised git model is that the merge commit messages generated in the fluture-template repo now don't carry over the issue number references correctly to the fluture-node repository. I guess Github assumed that its own context was the only context where this commit would appear when it generated that message.

I realized when merging the template into Monastic and Momi, but I couldn't come up with a solution.

**Review by dicearr — DISMISSED** [review]

**Comment by dicearr** [comment]
Is this still a breaking change after 8c9efdf?

**Comment by Avaq** [comment]
Yeah because `import it from 'fluture-node'` no longer resolves to the same value.

**Comment by Avaq** [comment]
Updated to include fluture-js/fluture-template#8

**Comment by Avaq** [comment]
Updated to bump fluture version

**Review by dicearr — APPROVED** [review]

**Pull request merged**
